baseURL: https://dorianrudolph.com/
languageCode: en-us
title: Dorian Rudolph
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: ":us:"
    weight: 1
    menu:
      main:
      # - name: Archive
      #   url: archives
      #   weight: 5
      - name: Search
        url: search/
        weight: 10
      - name: Imprint/Privacy
        url: imprint/
      # - name: Tags
      #   url: tags/
      #   weight: 10
      # - name: Categories
      #   url: categories/
      #   weight: 10

  de:
    languageName: ":de:"
    weight: 2
    profileMode:
      enabled: true
      title: Dorian Rudolph
      subtitle: Doktorand in Quanteninformatik an der [Universität Paderborn](https://en.cs.uni-paderborn.de/qi/team/group/dorian-rudolph)
      imageUrl: ../me.jpg
      imageTitle: me
      imageWidth: 300
      imageHeight: 300

    menu:
      main:
      # - name: Archive
      #   url: archives
      #   weight: 5
      - name: Suche
        url: search/
        weight: 10
      - name: Impressum/Datenschutz
        url: imprint/
      # - name: Tags
      #   url: tags/
      #   weight: 10
      # - name: Categories
      #   url: categories/
      #   weight: 10


params:
  env: production
  title: Dorian Rudolph
  author: Dorian Rudolph

  defaultTheme: auto # dark, light
  # disableThemeToggle: true
  # ShowShareButtons: true
  # ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowToc: true
  ShowAuthor: false
  # comments: false

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  profileMode:
    enabled: true
    title: Dorian Rudolph
    subtitle: >
      PhD Student in Quantum Informatics <br> at [Paderborn University](https://en.cs.uni-paderborn.de/qi/team/group/dorian-rudolph)
    imageUrl: me.jpg
    imageTitle: me
    imageWidth: 300
    imageHeight: 300
    # buttons:
    # - name: Archives
    #   url: archives
    # - name: Tags
    #   url: tags

  socialIcons:
  - name: email
    url: mailto:mail@dorianrudolph.com
  - name: github
    url: "https://github.com/DorianRudolph"
  - name: RsS
    url: "index.xml"

# menu:
#   main:
#   # - name: Archive
#   #   url: archives
#   #   weight: 10
#   - name: Search
#     url: search/
#     weight: 40
#   # - name: Tags
#   #   url: tags/
#   #   weight: 10
#   # - name: Categories
#   #   url: categories/
#   #   weight: 10
#   - name: Imprint/Privacy
#     url: imprint/
#     weight: 100

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
  - HTML
  - RSS
  - JSON
